# PostgreSQL Config Backup - Before Import Tuning
# Generated: Wed Jan 21 07:47:07 -03 2026

autovacuum = off
checkpoint_completion_target = 0.9
checkpoint_timeout = 1800s
effective_cache_size = 10485768kB
effective_io_concurrency = 0
fsync = off
full_page_writes = off
maintenance_work_mem = 2097152kB
max_parallel_workers = 8
max_parallel_workers_per_gather = 4
max_wal_size = 10240MB
max_worker_processes = 8
min_wal_size = 2048MB
random_page_cost = 4
shared_buffers = 5242888kB
synchronous_commit = off
wal_buffers = 20488kB
work_mem = 838656kB
